version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: foodhub-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foodhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    container_name: foodhub-redis
    ports:
      - "6379:6379"

  rabbitmq-mq:
    image: rabbitmq:3-management
    container_name: foodhub-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  postgres-data: